org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

minecraft_version=1.21.1
minecraft_version_range=[1.21.1]
neo_version=21.1.226
loader_version_range=[1,)

mod_id=infinitylights
mod_name=Styx's Infinity Lights
mod_license=GPL-3.0-only
mod_version=2.1.1
mod_group_id=com.infinitylights
mod_authors=Styx Admin & Codex
mod_logo_file=styx_infinity_lights_logo.png
mod_description=Giving players an incentive to venture into the Nether and to explore other means of lighting settlements, Styx's Infinity Lights adds permanent glowstone lights while vanilla coal-based torches, lanterns and campfires now burn out over time.
