org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

minecraft_version=1.20.1
minecraft_version_range=[1.20.1,1.21)
forge_version=47.2.0
forge_version_range=[47.2.0,)
loader_version_range=[47,)

mapping_channel=official
mapping_version=1.20.1

mod_id=infinitylights
mod_name=Styx's Infinity Lights
mod_license=GPL-3.0-only
mod_version=1.0.7
mod_group_id=com.infinitylights
mod_authors=Styx Admin & Codex
mod_logo_file=Styx_Infinity_Lights_Logo.png
mod_description=Giving players an incentive to venture into the Nether and to explore other means of lighting settlements, Styx's Infinity Lights replace Mojang's coal based light sources with recipes requiring glowstone while retaining the original block IDs to ensure compatibility with other modifications.
